config/routes.rb
Rails.application.routes.draw do
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    before_action :find_item, only: %i[show edit update destroy]

    def index
        @items = Item.all

    end

    def create
        item =Item.create(items_params)
        if item.persisted?
            redirect_to items_path
        else
            render json: item.errors, status: :unprocessable_entity
        end
    end

    def new

    end

    def show
        render body: 'Page not found', status: 404 unless @item
    end

    def edit
        render body: 'Page not found', status: 404 unless @item
    end

    def update
        if @item.update(items_params)
        redirect_to item_path
        else
            render json: item.errors, status: :unprocessable_entity
        end
    end

    def destroy
        if @item.destroy.destroyed?
            redirect_to items_path
        else
            render json: item.errors, status: :unprocessable_entity
        end
    end

    private

    def items_params
        params.permit(:owner, :name, :description)
    end

    def find_item
        @item = Item.where(id: params[:id]).first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h2>Edit new advertising</h2>
<h3><%= @item.owner %></h3>
<%= form_tag item_path(@item), method: :put do %>
    <%= label_tag :owner %>
    <%= text_field_tag :owner, @item.owner %>
    <%= label_tag :name %>
    <%= text_field_tag :name, @item.name %>
    <%= label_tag :description %>
    <%= text_field_tag :description, @item.description %>
    <%= submit_tag "Update" %>
    <% end %>

app/views/items/index.html.erb
<h1>All advertising</h1>

<% @items.each do |item| %>
<ul>
    <li><%= link_to item.owner, item_path(item) %></li>
    <li><%= item.name %></li>
    <li><%= item.description %></li>
    </ul>
    <%= button_to 'delete', item_path(item), method: :delete %>
<% end %>

<br/>

<%= link_to 'Create advertising', new_item_path %>

app/views/items/new.html.erb
<h2>Create new advertising</h2>

<%= form_tag items_path, method: :post do %>
    <%= label_tag :owner %>
    <%= text_field_tag :owner %>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
    <%= label_tag :description %>
    <%= text_field_tag :description %>
    <%= submit_tag "Save" %>
    <% end %>

app/views/items/show.html.erb
<h2>Show advertising</h2>

<h4>Owner: <%= @item.owner %></h4>

<ul>
    <li>Name: <%= @item.name %> </li>
    <li>Description: <%= @item.description %> </li>
</ul><br/>

<%= button_to "edit #{@item.owner}", edit_item_path %> <br/>
<%= button_to "delete #{@item.owner}", item_path(@item), method: :delete  %><br/>
<%= button_to "index", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Advertising</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>